 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Hello World</title>
    <style type="text/css">
        body 
        {
            background-color:#9b9;
        }
    </style>
</head>
<body>
    <h5>hello world template</h5>
    <?php echo $this->getChildHtml('top.links') ?>
</body>
</html> 
